version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
        auth:
          password: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: 
          name: Say hello
          command: echo Hello

workflows:
  version: 2.1
  workflow-0:
    jobs:
      - build
