version: 2.1

jobs:
  job-0:
    docker:
      - image: composer:2
        auth:
          username: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-{{ checksum "package-lock.json" }}
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
      - run:
          name: Install Node.js packages
          command: npm install
      - run:
          name: Install PHP packages
          command: composer install
      - run:
          name: Confirm sizes
          command: du -h -d 1
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
  job-1:
    docker:
      - image: cimg/base:2021.04
        auth:
          username: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-{{ checksum "package-lock.json" }}
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
      - run:
          name: Install Node.js packages
          command: npm install
      - run:
          name: Install PHP packages
          command: composer install

workflows:
  version: 2.1
  workflow-0:
    jobs:
      - job-0
      - job-1:
          requires:
            - job-0
